######################## default configuration ####################
baseURL = "https://example-working-group-website.netlify.app/"
title = "OpenCloneKit"
theme = "bigspring-light"
# post pagination
paginate = 3
# post excerpt
summaryLength = 15

# unsafe html
[markup.goldmark.renderer]
unsafe = true

theme = "bigspring-light"

[menu]
[[menu.main]]
identifier = "Home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "About"
name = "About"
title = "About"
url = "about/"
weight = 2

[[menu.main]]
identifier = "Partners"
name = "Partners"
title = "Partners"
url = "partners/"
weight = 3

#################### default parameters ################################
[params]
# logo = "images/logo.png"
# logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Manuel Lera-Ramirez"
favicon = "images/web/favicon.ico"
# image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

[params.variables]
# Blue combination
primary_color = "#3A80D2"
light = "#F0F7FF"
# Red combination
# primary_color = "#FF5733"
# light = "#FFE5D9"
# Orange combination
# primary_color = "#F59E0B"
# light = "#FEF3C7"
# Pink combination
# primary_color = "#EC4899"
# light = "#FDF2F8"
# Purple combination
# primary_color = "#8B5CF6"
# light = "#F9F5FF"


# # Preloader
# [[params.preloader]]
# enable = false
# preloader = "" # use jpg, png, svg or gif format.
