######################## default configuration ####################
BaseURL = "https://opencloning-landing-page.netlify.app/"
title = "OpenCloning"
theme = "bigspring-light"
# post pagination
# paginate = 3
# post excerpt
summaryLength = 15

# unsafe html
[markup.goldmark.renderer]
unsafe = true

theme = "bigspring-light"

[menu]
[[menu.main]]
identifier = "Home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "Getting Started"
name = "Getting Started"
title = "Getting Started"
url = "getting-started/"
weight = 2

[[menu.main]]
identifier = "People"
name = "People"
title = "People"
url = "people/"
weight = 3

[[menu.main]]
identifier = "Success stories"
name = "Success stories"
title = "Success stories"
url = "success-stories/"
weight = 4

[[menu.main]]
identifier = "Contact"
name = "Contact"
title = "Contact"
url = "contact/"
weight = 5

#################### default parameters ################################
[params]
# logo = "images/logo.png"
# logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "An Open-Source web application for DNA engineering"
author = "Manuel Lera-Ramirez"
favicon = "images/web/favicon.ico"
# image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

[params.variables]
# Blue combination
primary_color = "rgb(25, 118, 210)"
# light = "rgb(25, 118, 210)"
text_color = "#444"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#ECECEC"
black = "#000"
white = "#fff"

primary_font = "system-ui:wght@400"
primary_font_type = "sans-serif" # [serif/sans-serif]
# Red combination
# primary_color = "#FF5733"
# light = "#FFE5D9"
# Orange combination
# primary_color = "#F59E0B"
# light = "#FEF3C7"
# Pink combination
# primary_color = "#EC4899"
# light = "#FDF2F8"
# Purple combination
# primary_color = "#8B5CF6"
# light = "#F9F5FF"


# # Preloader
# [[params.preloader]]
# enable = false
# preloader = "" # use jpg, png, svg or gif format.


# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/solid.min.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.slim.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
# attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"