######################## default configuration ####################
baseURL = "https://openclonekit.netlify.app/"
title = "OpenCloneKit"
theme = "bigspring-light"
# post pagination
paginate = 3
# post excerpt
summaryLength = 15

# unsafe html
[markup.goldmark.renderer]
unsafe = true

theme = "bigspring-light"

[menu]
[[menu.main]]
identifier = "Home"
name = "Home"
title = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "Team"
name = "Team"
title = "Team"
url = "team/"
weight = 2

[[menu.main]]
identifier = "Partners"
name = "Partners"
title = "Partners"
url = "partners/"
weight = 3

[[menu.main]]
identifier = "Contact"
name = "Contact"
title = "Contact"
url = "contact/"
weight = 4

#################### default parameters ################################
[params]
# logo = "images/logo.png"
# logo_width = "200px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Manuel Lera-Ramirez"
favicon = "images/web/favicon.ico"
# image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

[params.variables]
# Blue combination
primary_color = "#3A80D2"
light = "#F0F7FF"
# Red combination
# primary_color = "#FF5733"
# light = "#FFE5D9"
# Orange combination
# primary_color = "#F59E0B"
# light = "#FEF3C7"
# Pink combination
# primary_color = "#EC4899"
# light = "#FDF2F8"
# Purple combination
# primary_color = "#8B5CF6"
# light = "#F9F5FF"


# # Preloader
# [[params.preloader]]
# enable = false
# preloader = "" # use jpg, png, svg or gif format.


# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.slim.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
# attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"